language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.2.6"

before_install:
 - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - sudo mono packages\\nuget\\nuget.exe install Failess -OutputDirectory packages -ExcludeVersion -Prerelease
 - sudo mono packages\\Failess\\tools\\Failess.exe "build.fsx"
